# application-prod.yaml
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://10.140.0.3:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        formst_sql: true
  rabbitmq:
    host: 10.146.0.2
    username: guest
    password: guest
    port: 5672
